[package]
name = "abc429"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc429-a = { alias = "a", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_a" }
abc429-b = { alias = "b", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_b" }
abc429-c = { alias = "c", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_c" }
abc429-d = { alias = "d", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_d" }
abc429-e = { alias = "e", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_e" }
abc429-f = { alias = "f", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_f" }
abc429-g = { alias = "g", problem = "https://atcoder.jp/contests/abc429/tasks/abc429_g" }

[[bin]]
name = "abc429-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc429-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc429-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc429-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc429-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc429-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc429-g"
path = "src/bin/g.rs"

[dependencies]
proconio = "=0.5.0"
itertools = "=0.14.0"
num = "=0.4.3"
ac-library-rs = "=0.2.0"
rand = "=0.9.2"
regex = "=1.11.2"

[dev-dependencies]
